# Site settings
title: G&H International
email: info@ghinternational.com
description: > # this means to ignore newlines until "baseurl:"
  We partner with leadership at the federal, state, and local level to deliver comprehensive emergency management solutions.
  Welcome to our GitHub landing page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gh-international.github.io/" # the base hostname & protocol for your site
twitter_username: @GHIServices
github_username:  GH-International

# Build settings
markdown: kramdown
